services:
  bpst-cluster:
    build:
      context: ..
      dockerfile: Dockerfile
    image: bpst:latest
    container_name: bpst-cluster
    environment:
      BPST_CONFIG_TEMPLATE: /etc/bpst/config.template.json
      BPST_CONFIG_OUTPUT: /etc/bpst/deployment.json
      BPST_CONFIG: /etc/bpst/deployment.json
      BPST_ADVERTISE_IP: ${BPST_ADVERTISE_IP:-127.0.0.1}
      BPST_BOOTSTRAP_IP: ${BPST_BOOTSTRAP_IP:-127.0.0.1}
    volumes:
      - ./config.template.json:/etc/bpst/config.template.json:ro
    ports:
      - "62000:62000"
      - "62001:62001"
      - "62010:62010"
      - "62020:62020"
    restart: unless-stopped
