services:
  bpst-cluster:
    image: fengzelinn/bpost:latest
    container_name: bpst-cluster
    environment:
      BPST_CONFIG_TEMPLATE: /etc/bpst/config.template.json
      BPST_CONFIG_OUTPUT: /etc/bpst/deployment.json
      BPST_CONFIG: /etc/bpst/deployment.json
      # 保留这些IP变量，因为 config.template.json 中的 peers 和 bootstrap 字段还需要它们
      INSTANCE1_IP: ${INSTANCE1_IP}
      INSTANCE2_IP: ${INSTANCE2_IP}
      INSTANCE3_IP: ${INSTANCE3_IP}
      INSTANCE4_IP: ${INSTANCE4_IP}
      INSTANCE5_IP: ${INSTANCE5_IP}
      INSTANCE6_IP: ${INSTANCE6_IP}
      INSTANCE7_IP: ${INSTANCE7_IP}
      INSTANCE8_IP: ${INSTANCE8_IP}
      INSTANCE9_IP: ${INSTANCE9_IP}
      INSTANCE10_IP: ${INSTANCE10_IP}
      INSTANCE11_IP: ${INSTANCE11_IP}
      INSTANCE12_IP: ${INSTANCE12_IP}
      INSTANCE13_IP: ${INSTANCE13_IP}
      INSTANCE14_IP: ${INSTANCE14_IP}
      INSTANCE15_IP: ${INSTANCE15_IP}
      INSTANCE16_IP: ${INSTANCE16_IP}
      INSTANCE17_IP: ${INSTANCE17_IP}
      INSTANCE18_IP: ${INSTANCE18_IP}
      INSTANCE19_IP: ${INSTANCE19_IP}
      INSTANCE20_IP: ${INSTANCE20_IP}
      INSTANCE21_IP: ${INSTANCE21_IP}
      INSTANCE22_IP: ${INSTANCE22_IP}
      INSTANCE23_IP: ${INSTANCE23_IP}
      INSTANCE24_IP: ${INSTANCE24_IP}
      INSTANCE25_IP: ${INSTANCE25_IP}
      INSTANCE26_IP: ${INSTANCE26_IP}
      INSTANCE27_IP: ${INSTANCE27_IP}
      INSTANCE28_IP: ${INSTANCE28_IP}
      INSTANCE29_IP: ${INSTANCE29_IP}
      INSTANCE30_IP: ${INSTANCE30_IP}
      INSTANCE31_IP: ${INSTANCE31_IP}
      INSTANCE32_IP: ${INSTANCE32_IP}
      INSTANCE33_IP: ${INSTANCE33_IP}
      INSTANCE34_IP: ${INSTANCE34_IP}
      INSTANCE35_IP: ${INSTANCE35_IP}
      INSTANCE36_IP: ${INSTANCE36_IP}
      INSTANCE37_IP: ${INSTANCE37_IP}
      INSTANCE38_IP: ${INSTANCE38_IP}
      INSTANCE39_IP: ${INSTANCE39_IP}
      INSTANCE40_IP: ${INSTANCE40_IP}
      INSTANCE41_IP: ${INSTANCE41_IP}
      INSTANCE42_IP: ${INSTANCE42_IP}
      INSTANCE43_IP: ${INSTANCE43_IP}
      INSTANCE44_IP: ${INSTANCE44_IP}
      INSTANCE45_IP: ${INSTANCE45_IP}
      INSTANCE46_IP: ${INSTANCE46_IP}
      INSTANCE47_IP: ${INSTANCE47_IP}
      INSTANCE48_IP: ${INSTANCE48_IP}
      INSTANCE49_IP: ${INSTANCE49_IP}
      INSTANCE50_IP: ${INSTANCE50_IP}
    volumes:
      - ./config.template.json:/etc/bpst/config.template.json:ro
    restart: unless-stopped
    command: ["deploy", "/etc/bpst/deployment.json"]
    # --- 添加下面这行，并删除 ports 部分 ---
    network_mode: "host"
